[llvm]
targets = "X86"
link-shared = true

[build]
docs = false
extended = true
#vendor = true  # Gunakan dependensi lokal
#offline = true  # Mode offline

[install]
prefix = "/opt/rustc-${RUST_VERSION}"
docdir = "share/doc/rustc-${RUST_VERSION}"

[rust]
channel = "stable"
rpath = false

[target.x86_64-unknown-linux-gnu]
llvm-config = "/usr/bin/llvm-config"

[target.i686-unknown-linux-gnu]
llvm-config = "/usr/bin/llvm-config"
#[source.crates-io]
#replace-with = "local-registry"

#[source.local-registry]
#directory = "~/.cargo/registry/index"

EOF
